/* DO NOT EDIT THIS FILE */

// stdio.h provides I/O functions such as `scanf` and `printf`
#include <stdio.h>

// Include the solution.h header file, which contains the function definitions for functions
// implemented in solution.c.
#include "solution.h"

/**
 * The main function is called when the program is run. A return value of 0 indicates the program
 * ran successfully, while a non-zero return value indicates otherwise. The return value of the main
 * function in C corresponds to the "exit code" of the program.
 */
int main() {
    double di, df;

    /* Read input */

    // `printf` prints formatted output
    printf("Enter initial orbit distance: ");
    // `scanf` reads input to the program
    if (scanf("%lf", &di) != 1) {
        printf("Invalid input\n");
        return 1;
    }

    printf("Enter final orbit distance: ");
    if (scanf("%lf", &df) != 1) {
        printf("Invalid input\n");
        return 1;
    }

    /* Check input validity */

    if (check_input_validity(di, df)) {
        printf("Invalid input\n");
        return 1;
    }

    /* Display the computed values */

    printf("Initial change in velocity: %.2f km/s\n", get_initial_velocity_change(di, df));
    printf("Final change in velocity: %.2f km/s\n", get_final_velocity_change(di, df));
    printf("Transfer time: %.2f hr\n", get_time(di, df));

    /* Exit */

    return 0;
}
