# # Rename this file `Makefile` and include it in your submission if you use it.

# # Replace `encounters.c` with the name of your file, or name your file `encounters.c`.
# #           vvvvvvvvvvvv
# encounters: solvemaze.c
# 	gcc -o $@ $^

# .PHONY: clean
# clean:
# 	rm -f solvemaze
# Define the compiler and compiler flags
# newbusroutes:
# 	gcc newbusroutes.c -o newbusroutes 
# tab it 
# @ will be the variable of the filenamer
practice: practice.c
	gcc $^ -o $@
# if i want to grab multiple files just follow with the files with a space