#pragma once

/* DO NOT EDIT THIS FILE */

// Below are declarations of the functions to be implemented in `solution.c`. The function
// signatures in `solution.c` must match these declarations.

int check_input_validity(double di, double df);
double get_initial_velocity_change(double di, double df);
double get_final_velocity_change(double di, double df);
double get_time(double di, double df);
