/* DO NOT EDIT THIS FILE */

#include <stdio.h>
// This include is needed for the `atof` function.
#include <stdlib.h>

#include "returnvalues.h"

/**
 * The main function can take two arguments, which are used to process command-line arguments. The
 * first argument (`argc`) is the number of command-line arguments. The second (`argv`) is an array
 * containing the arguments themselves as strings.
 *
 * Note that the name of the executable file is always treated as the first argument.
 */
int main(int argc, char** argv) {
    double p, maxval;
    int maxidx;
    MaxStruct maxstruct;

    if (argc != 2) {
        printf("Exactly one command-line argument should be passed\n");
        return 1;
    }

    if ((p = atof(argv[1])) == 0) {
        printf("The command-line argument should be a non-zero number\n");
        return 1;
    }

    approach1(p, &maxval, &maxidx);
    printf("Approach 1: maxval = %.3f, maxidx = %d\n", maxval, maxidx);

    maxval = approach2(p, &maxidx);
    printf("Approach 2: maxval = %.3f, maxidx = %d\n", maxval, maxidx);

    maxstruct = approach3(p);
    printf("Approach 3: maxval = %.3f, maxidx = %d\n", maxstruct.maxval, maxstruct.maxidx);

    return 0;
}
