#pragma once

/* DO NOT EDIT THIS FILE */

/*
 * This is the struct to use for approach 3 of this workshop.
 */
typedef struct MaxStruct {
    double maxval;
    int maxidx;
} MaxStruct;

void approach1(double p, double* maxval, int* maxidx);
double approach2(double p, int* maxidx);
MaxStruct approach3(double p);
